### ISSUE TITLE
StartupWMClass=winbox.exe

### ISSUE THREAD

**Issue by lessneek** [panaceya/winbox#10]
Please add `StartupWMClass=winbox.exe` to the .desktop file to correctly display a running app in a single icon, but not two - one winbox and second a wine. GNOME.

**Comment by panaceya** [comment]
Sanks, now merged. Please wait some time for update available.

**Comment by lessneek** [comment]
panaceya, have you tested it? I'm not sure it will actually fix it in a `snap` case of running of a wine app.
