### ISSUE TITLE
The following packages have unmet dependencies:  winehq-stable : Depends: wine-stable (= 6.0.1~hirsute-1) E: Unable to correct problems, you have held broken packages.

### ISSUE THREAD

**Issue by Younz-code** [panaceya/winbox#16]
The following packages have unmet dependencies:
 winehq-stable : Depends: wine-stable (= 6.0.1~hirsute-1)
E: Unable to correct problems, you have held broken packages.

**Comment by panaceya** [comment]
Please provide more information.
