### ISSUE TITLE
Winbox cannot save data

### ISSUE THREAD

**Issue by qiet72** [panaceya/winbox#17]
After installing winbox via snap install command, I try to run winbox.  Winbox comes up, I connect to a router, open some windows and move them in place, then close winbox.  The next time I open winbox, the session is not saved and the window positions are reset to defaults.  The snap installation does create a ~/snap/winbox directory structure.

If I install winbox outside of the snap environment, winbox can save it sessions and window positions.

**Comment by qiet72** [comment]
Environment:
OS: Ubuntu 18.04.5
HW: Lenovo ThinkPad T470

**Comment by dcheek2** [comment]
same issue, ubuntu 21.04 Thinkpad T500

**Comment by geosoft1** [comment]
same issue here on ubuntu 20.04

**Comment by HonzaCZ** [comment]
I suggest closing this ticket because my pull request #33 has resolved this issue.
