### ISSUE TITLE
issue on debian bulleyes when installing winbox

### ISSUE THREAD

**Issue by yeahgith** [panaceya/winbox#40]
after doing snapcraft, this the result...

-------------------------------------------------
+ snapcraftctl set-version 3.39+git
Staging winbox 
+ snapcraftctl stage
Priming winbox 
+ snapcraftctl prime
The interpreter 'bash' for 'winbox' was resolved to '/bin/bash'.
The command 'winbox' has been changed to '/bin/bash $SNAP/winbox' to safely account for the interpreter.
A shell wrapper will be generated for command '/bin/bash $SNAP/winbox' as it does not conform with the command pattern expected by the runtime. Commands must be relative to the prime directory and can only consist of alphanumeric characters, spaces, and the following special characters: / . _ # : $ -
Snapping |                                                           
Snapped winbox_3.39_amd64.snap
-------------------------------------------------

then i try to run winbox, this the result...

-------------------------------------------------

root@debian:~/winbox# winbox 
2023/09/24 09:00:29.827082 cmd_run.go:1055: WARNING: cannot start document portal: write unix @->/run/user/1000/bus: write: broken pipe
mkdir: cannot create directory ‘/run/user/0’: Permission denied
/snap/winbox/121/winbox: line 287: wine: command not found
/snap/winbox/121/winbox: line 335: notify-send: command not found
cp: target '/run/user/0/snap.winbox/' is not a directory

-----------------------------------------------------

do have any idea...?
thanks

**Comment by panaceya** [comment]
Cannot reproduce.

**Comment by fluidum** [comment]
Works on my bullseye. It broke when running it via CLI as root. snap remove/install made it work again.

So try starting winbox under your logged in user using search box.
