### ISSUE TITLE
The md5 hash for winbox64.exe within this snap differs from Mikrotik's website

### ISSUE THREAD

**Issue by ayubio** [panaceya/winbox#42]
I've installed this snap and compared the md5sum result for the winbox64.exe file obtained from the snap and the one obtained from https://download.mikrotik.com/winbox/3.40/winbox64.exe - Both executables are Winbox 3.40 version and I noticed the md5 hashes does not match as I demonstate below:

```
$ md5sum /snap/winbox/123/usr/libexec/winbox64.exe
048e1265d4db9196583e9d23ad4d70d5  /snap/winbox/123/usr/libexec/winbox64.exe
$ wget -q https://download.mikrotik.com/winbox/3.40/winbox64.exe;md5sum winbox64.exe
0b5da86bd6f2603b9427a18d192b61b6  winbox64.exe
```

While I can find results for 0b5da86bd6f2603b9427a18d192b61b6 on Google search engine (with links directing to mikrotik.com official website), the hash 048e1265d4db9196583e9d23ad4d70d5 was never mentioned before.

Shouldn't both files be exactly the same? Why the binary provided by this package is not the same provided by the official manufacturer website?

** `snap version` **
```
ayub@indaiatuba:/tmp$ snap info winbox
name:      winbox
summary:   small utility that allows administration of MikroTik RouterOS
publisher: ThePanaceya
store-url: https://snapcraft.io/winbox
license:   unset
description: |
  Winbox is a small utility that allows administration of MikroTik RouterOS using a fast and simple
  GUI.
  
  Snap conatins Wine runtime and winbox client.
  
  Readme: https://github.com/panaceya/winbox/blob/main/README.md
snap-id: UdK6K4ZjRfjL0wRFh0tWGO7vPhA4Qge4
channels:
  latest/stable:    3.40 2023-10-16 (123) 47MB -
  latest/candidate: ↑                          
  latest/beta:      ↑                          
  latest/edge:      ↑ 
```

**Comment by ochristi** [comment]
If you make a sha25sum of both file versions, you can find references to both checksums
```
09e9683e008d09c981e4a5294c78f93e03dede1af19aee8ba794f5ca4aedef04  /snap/winbox/current/usr/libexec/winbox64.exe
91f7b0456619dbfc19940a85566c949ce3718321f32709886df5125c71f0b6b7  winbox64.exe
```
My best guess is, that they put a slightly updated version on their website after the snap package was built.

With `dhex` on both binaries, I can only find some differences on a region regarding some certificate changes.

**Comment by panaceya** [comment]
> I've installed this snap and compared the md5sum result for the winbox64.exe file obtained from the snap and the one obtained from https://download.mikrotik.com/winbox/3.40/winbox64.exe - Both executables are Winbox 3.40 version and I noticed the md5 hashes does not match as I demonstate below:
> 
> ```
> $ md5sum /snap/winbox/123/usr/libexec/winbox64.exe
> 048e1265d4db9196583e9d23ad4d70d5  /snap/winbox/123/usr/libexec/winbox64.exe
> $ wget -q https://download.mikrotik.com/winbox/3.40/winbox64.exe;md5sum winbox64.exe
> 0b5da86bd6f2603b9427a18d192b61b6  winbox64.exe
> ```
> 
> While I can find results for 0b5da86bd6f2603b9427a18d192b61b6 on Google search engine (with links directing to mikrotik.com official website), the hash 048e1265d4db9196583e9d23ad4d70d5 was never mentioned before.
> 
> Shouldn't both files be exactly the same? Why the binary provided by this package is not the same provided by the official manufacturer website?
> 
> ** `snap version` **
> 
> ```
> ayub@indaiatuba:/tmp$ snap info winbox
> name:      winbox
> summary:   small utility that allows administration of MikroTik RouterOS
> publisher: ThePanaceya
> store-url: https://snapcraft.io/winbox
> license:   unset
> description: |
>   Winbox is a small utility that allows administration of MikroTik RouterOS using a fast and simple
>   GUI.
>   
>   Snap conatins Wine runtime and winbox client.
>   
>   Readme: https://github.com/panaceya/winbox/blob/main/README.md
> snap-id: UdK6K4ZjRfjL0wRFh0tWGO7vPhA4Qge4
> channels:
>   latest/stable:    3.40 2023-10-16 (123) 47MB -
>   latest/candidate: ↑                          
>   latest/beta:      ↑                          
>   latest/edge:      ↑ 
> ```

As I see it, these are two different builds of the winbox, which are downloaded from the Mikrotik website. The application that is included in SNAP is loaded during assembly on the [launchpad build](https://launchpad.net/~build.snapcraft.io/+snap/91a6fef1e0c3191001941d8176affc27/+build/2285407).
