### ISSUE TITLE
Neighbor is not listed in RBs without IP

### ISSUE THREAD

**Issue by cairoapcampos** [panaceya/winbox#43]
Winbox does not find a neighbor when connected directly to an RB that does not have an IP. I want to configure a new RB that does not have a defined IP. Therefore, I would like to access the equipment via the mac address of an ethernet interface. On Windows systems this is possible, but on Linux I haven't managed it yet. Can you guide me why it's not working?

I have already run the **sudo ufw allow 5678/udp** command on Linux Mint.

I noticed that via the network, Winbox lists RBs in production as neighbors. The problem occurs on new RBs that I try to access via mac address.

**Comment by panaceya** [comment]
Does it access the device by IP address?
