### ISSUE TITLE
Firewall 

### ISSUE THREAD

**Issue by mil2house** [panaceya/winbox#46]
**Is your feature request related to a problem? Please describe.**
I am use UFW firewall on my PC. After adding port UDP 5678 "Neighbors" works fine. 
Wine64-preloader uses also port to communicate with RouterOS, but every time other port.
![obrazek](https://github.com/panaceya/winbox/assets/68024556/ca985d11-94b6-4342-8422-f88bc6e56919)

**Describe the solution you'd like**
I am do not know. :-/

**Describe alternatives you've considered**
Apply default port for Wine? Any rule for UFW?

Thanks You.

**Comment by panaceya** [comment]
Please refer to the firewall documentation, this question is not related to the project.
