### ISSUE TITLE
Failed to run 'override-build': Exit code was 8

### ISSUE THREAD

**Issue by NOCKevyn** [panaceya/winbox#49]
It gives the following error > wget -O winbox32.exe https://download.mikrotik.com/winbox/3.40/winbox.exe
--2024-04-30 10:06:20-- https://download.mikrotik.com/winbox/3.40/winbox.exe
Resolving download.mikrotik.com (download.mikrotik.com)... 159.148.147.251, 2a02:610:7501:3000::251
Connecting to download.mikrotik.com (download.mikrotik.com)|159.148.147.251|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-04-30 10:06:21 ERROR 403: Forbidden.

Failed to run 'override-build': Exit code was 8.
Run the same command again with --debug to shell into the environment if you wish to introspect this failure.

**Comment by panaceya** [comment]
Fixed in #53.
