### ISSUE TITLE
bug report winbox

### ISSUE THREAD

**Issue by anmr2380** [panaceya/winbox#50]
winbox does not start on ubuntu desktop 24.04 gnome 46 wayland does not show the graphical interface

**Comment by rodrigocorazza** [comment]
I have the same problem, i'm using Ubuntu Budgie 24.04

**Comment by panaceya** [comment]
Fixed in #53. 
You need before refresh by `snap refresh winbox --stable`.

**Comment by anmr2380** [comment]
👍🏻👍🏻👍🏻I will do anything I will report
