### ISSUE TITLE
Keep last connection data persistent

### ISSUE THREAD

**Issue by gil-obradors** [panaceya/winbox#7]
**Is your feature request related to a problem? Please describe.**

I think last connection info can be found `drive_c/users/<user>/Application\ Data/Mikrotik/Winbox/settings.cfg.vi`
Could be fine to persist this file

**Describe the solution you'd like**
I don't know how snap works. 
May be the file must be copied at start and saved to user local snap persistent dir of this app ?

**Describe alternatives you've considered**

**Additional context**

The log of winbox without snap:

```
saving settings to .\viw2dc9.tmp... for C:\users\gil\Application Data\Mikrotik\Winbox\settings.cfg.viw
[..]
loadConfig C:\users\gil\Application Data\Mikrotik\Winbox\Addresses.cdb
[...]
saving settings to .\viwc5be.tmp... for C:\users\gil\Application Data\Mikrotik\Winbox\settings.cfg.viw
```

Addresses is working fine, is only the last connection data
![imatge](https://user-images.githubusercontent.com/6016929/106377757-a8ed3580-639f-11eb-9a59-2da21d97c2eb.png)

**Comment by akoscomp** [comment]
I have the same problem with this version of winbox. Before I use winbox run directly with wine, and works well. When I switch to this snap version the winbox don't keep the connection data.
